version: '3.8'

services:
  backend:
    image: prizrak1993laureata/taski_backend:latest
    restart: always
    environment:
      - DEBUG=False
    volumes:
      - static_volume:/app/collected_static

  frontend:
    image: prizrak1993laureata/taski_frontend:latest
    restart: always
    depends_on:
      - backend

  gateway:
    image: prizrak1993laureata/taski_gateway:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  static_volume:
